export type {
  DomainEvent,
  DomainEventType,
  EventEnvelope,
  HubRegistered,
  RouteRegistered,
  PackageCreated,
  PackageScanned,
  PackageArrivedAtHub,
  TrailerDeparted,
  TrailerArrivedAtHub,
  TrailerDocked,
  Severity,
  RfidObserved,
  WrongTrailerDetected,
  MissedUnloadDetected,
  PlanGenerated,
  PlanAccepted,
  DriverRegistered,
  DriverAssignedToTrip,
  DriverDutyStateChanged,
  DriverSwappedAtHub,
  UnloadStarted,
  LoadStarted,
  UnloadCompleted,
} from "./domain-event.js";
export { assertNever } from "./domain-event.js";
export {
  EVENT_SCHEMA_VERSION,
  domainEventSchema,
  hubRegisteredSchema,
  routeRegisteredSchema,
  packageCreatedSchema,
  packageScannedSchema,
  packageArrivedAtHubSchema,
  trailerDepartedSchema,
  trailerArrivedAtHubSchema,
  trailerDockedSchema,
  severitySchema,
  rfidObservedSchema,
  wrongTrailerDetectedSchema,
  missedUnloadDetectedSchema,
  planGeneratedSchema,
  planAcceptedSchema,
  driverRegisteredSchema,
  driverAssignedToTripSchema,
  driverDutyStateChangedSchema,
  driverSwappedAtHubSchema,
  unloadStartedSchema,
  loadStartedSchema,
  unloadCompletedSchema,
} from "./schemas.js";
