/**
 * MSW browser worker for the Vitest `browser` project (`*.browser.test.tsx`).
 *
 * In browser mode the in-page Service Worker (served from `public/
 * mockServiceWorker.js`, generated by `npx msw init public`) intercepts the same
 * `/api/*` surface as the node server, so a `<MapView/>` smoke test renders
 * against deterministic fixtures rather than the live OSM/API.
 *
 * The MapView geo fetch fails gracefully (the basemap still mounts), so the
 * smoke test does not strictly depend on the worker; it is wired here so future
 * browser tests that DO need API data can `await worker.start()`.
 */
import { setupWorker } from "msw/browser";
import { handlers } from "./handlers.js";

/** The shared browser-side MSW worker for the browser project. */
export const worker = setupWorker(...handlers);
